### Base URL
@baseUrl = http://127.0.0.1:8000/api
@token = Bearer 10|5gluH8Q8dR0EzkTNIGjlgZOCmpu5feALGAm5EYvLbcab6a7a

//=========================================== WAREHOUSE CONTROLLER ============================================
### GET all warehouse
GET {{baseUrl}}/warehouse
Accept: application/json
Authorization: {{token}}

### Create a new warehouse
POST {{baseUrl}}/warehouse
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
    "name": "Warehouse name C",
    "location": "Street ABC Block XYZ"
}

### Show?
GET {{baseUrl}}/warehouse/2
Accept: application/json
Authorization: {{token}}

### Update
PUT {{baseUrl}}/warehouse/2
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
    "name": "Warehouse name AAAAAAAAAAAA"
}

### Delele a wareshouse
DELETE {{baseUrl}}/warehouse/2
Accept: application/json
Authorization: {{token}}

//=======================================CATEGORY CONTROLLER=========================================
###Get all the categories record
GET {{baseUrl}}/category
Accept: application/json
Authorization: {{token}}

###Create a new category
POST {{baseUrl}}/category/create
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
    "name": "Porceiline"
}

###Get by id
GET {{baseUrl}}/category/9
Accept: application/json
Authorization: {{token}}

###Update by id
PUT {{baseUrl}}/category/update/9
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
    "name": "updated name"
}

###Delete by id
DELETE {{baseUrl}}/category/delete/8
Accept: application/json
Authorization: {{token}}

//========================================= SupplierController =============================================
###Get all supplier
GET {{baseUrl}}/supplier
Accept: application/json
Authorization: {{token}}

###Create a new supplier
POST {{baseUrl}}/supplier/create
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
    "name": "Asus",
    "email": "kotatstu0303@gmail.com",
    "phone": "0123456789"
}

###Get by id
GET {{baseUrl}}/supplier/6
Accept: application/json
Authorization: {{token}}

###update
PUT {{baseUrl}}/supplier/update/6
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
    "name": "updated name Acer"
}

###Delete by id
DELETE {{baseUrl}}/supplier/delete/6
Accept: application/json
Authorization: {{token}}

//========================================= PRODUCT CONTROLLER ============================================
###
GET {{baseUrl}}/product
Accept: application/json
Authorization: {{token}}

###Create new product
POST {{baseUrl}}/product/create
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
    "name": "Product name EBF",
    "sku": "EBF-001",
    "category_id": 1,
    "supplier_id": 1
}

###Get by id
GET {{baseUrl}}/product/4
Accept: application/json
Authorization: {{token}}

###Update
PUT {{baseUrl}}/product/update/4
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
    "name": "Updated USB Cable",
    "sku": "USB-005"
}

###Delete by id
DELETE  {{baseUrl}}/product/delete/4
Accept: application/json
Authorization: {{token}}

//============================================== STOCK CONTROLLER ===============================================================
###Get all stock
GET {{baseUrl}}/stock
Accept: application/json
Authorization: {{token}}

###Create new stock
POST {{baseUrl}}/stock/create
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
    "warehouse_id": 1,
    "product_id": 1,
    "quantity": 100
}

###Get by id
GET {{baseUrl}}/stock/5
Accept: application/json
Authorization: {{token}}

###Update by id
PUT {{baseUrl}}/stock/update/5
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
    "quantity": 999
}

###delete by id
DELETE {{baseUrl}}/stock/delete/5
Accept: application/json
Authorization: {{token}}

//======================================================= PurchaseOrderController =================================
###Get all
GET {{baseUrl}}/purchaseOrder
Accept: application/json
Authorization: {{token}}

###Create new
POST {{baseUrl}}/purchaseOrder/create
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
      "reference": "Token Test",
      "supplier_id": 1,
      "status": "Pending",
      "items":
      [
        {
            "product_id": 1,
            "quantity": 100
        },
        {
            "product_id": 3,
            "quantity": 100
        }
      ]
}

###Get by id
GET {{baseUrl}}/purchaseOrder/2
Accept: application/json
Authorization: {{token}}

###Update by id
PUT {{baseUrl}}/purchaseOrder/update/2
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
    "status": "Pending"
}

###Delete by id
DELETE {{baseUrl}}/purchaseOrder/delete/3
Accept: application/json
Authorization: {{token}}

###Received an order, called service layer
POST {{baseUrl}}/purchaseOrder/11/receive
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
    "warehouse_id": 2,
    "items":
    [
        {
            "purchase_order_item_id": 11,
            "quantity": 100
        },

        {
            "purchase_order_item_id": 12,
            "quantity": 100
        }

    ]
}

//============================================== STOCK EXPORT CONTROLLER =========================================
###Get all
GET {{baseUrl}}/stockExport
Accept: application/json
Authorization: {{token}}

###Create new record
POST {{baseUrl}}/stockExport/create
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
  "reference": "EXP-1003",
  "warehouse_id": 1,
  "destination": "Downtown Shop",
  "items": [
    {
        "product_id": 1, "quantity": 10
    }
  ]
}

###Get by id
GET {{baseUrl}}/stockExport/1
Accept: application/json
Authorization: {{token}}

###Update by id
PUT {{baseUrl}}/stockExport/update/1
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
    "destination": "AAAAAAAAAAAAAAAAAAAAAAAA"
}

###Delete by id
DELETE {{baseUrl}}/stockExport/delete/1
Accept: application/json
Authorization: {{token}}

###Disaptch
POST {{baseUrl}}/stockExport/4/dispatch
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
  "items": [
    {
        "stock_export_item_id": 4, "quantity": 10
    }
  ]
}

//=========================================== Authentications =======================================
###Register new user
POST {{baseUrl}}/register
Content-Type: application/json
Accept: application/json

{
    "name": "user123",
    "email": "kotatstu0303@gmail.com",
    "password": "12345678"
}

###Login
POST {{baseUrl}}/login
Content-Type: application/json
Accept: application/json

{
    "email": "kotatstu0303@gmail.com",
    "password": "12345678"
}
