### Base URL
@baseUrl = http://127.0.0.1:8000/api

//=========================================== WAREHOUSE CONTROLLER ============================================
### GET all warehouse
GET {{baseUrl}}/warehouse

### Create a new warehouse
POST {{baseUrl}}/warehouse
Content-Type: application/json

{
    "name": "Warehouse name C",
    "location": "Street ABC Block XYZ"
}

### Show?
GET {{baseUrl}}/warehouse/2

### Update
PUT {{baseUrl}}/warehouse/2
Content-Type: application/json

{
    "name": "Warehouse name AAAAAAAAAAAA"
}

### Delele a wareshouse
DELETE {{baseUrl}}/warehouse/2

//=======================================CATEGORY CONTROLLER=========================================
###Get all the categories record
GET {{baseUrl}}/category

###Create a new category
POST {{baseUrl}}/category/create
Content-Type: application/json

{
    "name": "Porceiline"
}

###Get by id
GET {{baseUrl}}/category/9

###Update by id
PUT {{baseUrl}}/category/update/9
Content-Type: application/json

{
    "name": "updated name"
}

###Delete by id
DELETE {{baseUrl}}/category/delete/8

//========================================= SupplierController =============================================
###Get all supplier
GET {{baseUrl}}/supplier

###Create a new supplier
POST {{baseUrl}}/supplier/create
Content-Type: application/json

{
    "name": "Asus",
    "email": "kotatstu0303@gmail.com",
    "phone": "0123456789"
}

###Get by id
GET {{baseUrl}}/supplier/6


###update
PUT {{baseUrl}}/supplier/update/6
Content-Type: application/json

{
    "name": "updated name Acer"
}


###Delete by id
DELETE {{baseUrl}}/supplier/delete/6

//========================================= PRODUCT CONTROLLER ============================================
###
GET {{baseUrl}}/product

###Create new product
POST {{baseUrl}}/product/create
Content-Type: application/json

{
    "name": "Product name F",
    "sku": "F-001",
    "category_id": 1,
    "supplier_id": 2
}

###Get by id
GET {{baseUrl}}/product/4

###Update
PUT {{baseUrl}}/product/update/4
Content-Type: application/json

{
    "name": "Updated USB Cable",
    "sku": "USB-005"
}

###Delete by id
DELETE  {{baseUrl}}/product/delete/4

//============================================== STOCK CONTROLLER ===============================================================
###Get all stock
GET {{baseUrl}}/stock

###Create new stock
POST {{baseUrl}}/stock/create
Content-Type: application/json

{
    "warehouse_id": 3,
    "product_id": 3,
    "quantity": 10
}

###Get by id
GET {{baseUrl}}/stock/5

###Update by id
PUT {{baseUrl}}/stock/update/5
Content-Type: application/json

{
    "quantity": 999
}

###delete by id
DELETE {{baseUrl}}/stock/delete/5

//======================================================= PurchaseOrderController =================================
###Get all
GET {{baseUrl}}/purchaseOrder

###Create new
POST {{baseUrl}}/purchaseOrder/create
Content-Type: application/json

{
      "reference": "Greyrat",
      "supplier_id": 1,
      "status": "Pending",
      "items": 
      [
        {
            "product_id": 2,
            "quantity": 69
        },
        {
            "product_id": 3,
            "quantity": 100
        }
      ]
}

###Get by id
GET {{baseUrl}}/purchaseOrder/2

###Update by id
PUT {{baseUrl}}/purchaseOrder/update/2
Content-Type: application/json

{
    "status": "Pending"
}

###Delete by id
DELETE {{baseUrl}}/purchaseOrder/delete/3

###Received an order, called service layer
POST {{baseUrl}}/purchaseOrder/10/receive
Content-Type: application/json

{
    "warehouse_id": 2,
    "items":
    [
        {
            "purchase_order_item_id": 9,
            "quantity": 19
        },

        {
            "purchase_order_item_id": 10,
            "quantity": 100
        }

    ]
}